### ISSUE TITLE
Eigenvalues did not converge

### ISSUE THREAD

**Issue by statsqixu** [davidhallac/TICC#11]
Hi, David, thanks for your great job. When I run this script with my data, I always meet the following problem:

Traceback (most recent call last):
  File "example.py", line 6, in <module>
    (cluster_assignment, cluster_MRFs) = TICC.solve(window_size = 2,number_of_clusters = 4, lambda_parameter = 11e-2, beta = 600, maxIters = 100, threshold = 2e-5, write_out_file = False, input_file = fname, prefix_string = "output_folder/", num_proc=1)
  File "/Users/apple/github/TICC/TICC_solver.py", line 138, in solve
    val = optRes[cluster].get()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/pool.py", line 567, in get
    raise self._value
numpy.linalg.linalg.LinAlgError: Eigenvalues did not converge

And Before this problem, it also has this following warning:
RuntimeWarning: Degrees of freedom <= 0 for slice
  S = np.cov(np.transpose(D_train) )
/Users/apple/Library/Python/2.7/lib/python/site-packages/numpy/lib/function_base.py:3093: RuntimeWarning: divide by zero encountered in double_scalars
  c *= 1. / np.float64(fact)
/Users/apple/Library/Python/2.7/lib/python/site-packages/numpy/lib/function_base.py:3093: RuntimeWarning: invalid value encountered in multiply
  c *= 1. / np.float64(fact)

Is there any problem of my data or anything? I hope you can help me, thanks!

**Comment by venkata-mi** [comment]
I'm trying to use the same algorithm to cluster my Time series data. I tweaked the parameters but still no gold.

**Comment by sagarvare** [comment]
Could you try increasing the lambda_parameter? Try a bunch of values like
0.5, 1, 10


On Dec 11, 2017 8:02 AM, "Venkata Sai Sriram Pillutla" <
notifications@github.com> wrote:

I'm trying to use the same algorithm to cluster my Time series data. I
tweaked the parameters but still no gold.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/davidhallac/TICC/issues/11#issuecomment-350768618>, or mute
the thread
