### ISSUE TITLE
Missing in car.py -> "saves a .csv file with list of the assignments for each of the timestamps to the 'k' clusters "

### ISSUE THREAD

**Issue by Ejaz125** [davidhallac/TICC#14]
Hello,
Thank you for providing the code!
I am using the same type of signals as used in the paper on the car.py file. The code runs without any error generating few text files. As mentioned in the description, car.py should return a .csv file with cluster assignments for each timestamps. However, I could not find a .csv file with cluster assignments. Am I missing anything in the code or the snippet is missing?

**Comment by davidhallac** [comment]
Hi,

Yes, you are correct that it doesn't save the cluster assignments directly. You can save them, however, by saving the "clustered_points" variable, since that is the list you are looking for. (The car.py code saves the clusters as an RGB list in the file ending with "color_file_EM.txt").

Hope that helps!
