### ISSUE TITLE
How can BIC be utilized for determining the optimal number of clusters?

### ISSUE THREAD

**Issue by arpnomic** [davidhallac/TICC#60]
Is there a way to determine the most optimal number of clusters?

**Comment by RasmusFonseca** [comment]
In my opinion, no, because the definition of cluster quality is subjective and domain specific. You'll need to run TICC multiple times to get different assignments and see which works best for you. I've done this with different values of `number_of_clusters` and then compared how they break down .. to some extent comparable to hierarchical clustering. When interval boundaries started to change just from adding more clusters I concluded that it was overfitting. 

This little tool might be useful to illustrate your cluster assignments: https://gpcrviz.github.io/ChangePointDetection/DisplayIntervals/
